### ISSUE TITLE
Remove iOS support flag

### ISSUE THREAD

**Issue by NathanaelA** [milannankov/nativescript-radio#1]
Hey thanks for creating a plugin for NativeScript.     

I'm the guy behind PNR (https://plugins.nativescript.rocks), and PNR and NativeScript itself; uses the https://github.com/milannankov/nativescript-radio/blob/master/src/package.json#L10 `ios` flag to detect if the plugin actually supports iOS.    Looking at the code base, I don't see any ios support.     So if you don't mind please remove that in the next release so that the plugin shows up properly as Android only on the plugin sites...   :-)    At the point you do add iOS support, then you re-add the flag and the data will automatically be fixed on PNR.   Please note I do have some documentation on publishing flags at https://plugins.nativescript.rocks/create

**Comment by milannankov** [comment]
Sure, I will do that. Thanks for giving me heads up.
